### ISSUE TITLE
Error running the zkey-manager-compile script 

### ISSUE THREAD

**Issue by amit0365** [weijiekoh/circom-helper#7]
main.cpp:9:10: fatal error: 'nlohmann/json.hpp' file not found
<img width="378" alt="Screen Shot 2023-04-05 at 11 22 21 PM" src="https://user-images.githubusercontent.com/47255508/230264277-bd00b2bc-75ea-4931-861a-f39404476899.png">

**Comment by weijiekoh** [comment]
Please install the dependencies first. If you're on Ubuntu, run:

```bash
sudo apt-get install libgmp-dev nlohmann-json3-dev nasm g++
```
